/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    "service-groups": ServiceGroup;
    services: Service;
    "funding-programs": FundingProgram;
    faqs: Faq;
    testimonials: Testimonial;
    downloads: Download;
    pages: Page;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "service-groups": ServiceGroupsSelect<false> | ServiceGroupsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    "funding-programs": FundingProgramsSelect<false> | FundingProgramsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ("false" | "none" | "null") | false | null | ("en" | "el") | ("en" | "el")[];
  globals: {
    settings: Setting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: "en" | "el";
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff accounts and their roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Determines what this person can do (docs/14).
   */
  role:
    | "super-admin"
    | "site-admin"
    | "community-care-manager"
    | "marketing-manager"
    | "editor"
    | "translator"
    | "reviewer"
    | "read-only";
  /**
   * Sites this person may manage. Leave empty for none until assigned.
   */
  sites?: ("gocsa-community-care" | "rgha-retirement-living")[] | null;
  status?: ("active" | "disabled") | null;
  lastLoginAt?: string | null;
  failedLoginCount?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * Images and documents, reused across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title: string;
  /**
   * Tick only for purely decorative images (they get empty alt text).
   */
  isDecorative?: boolean | null;
  /**
   * Describe the image for screen readers. Required unless decorative.
   */
  altText?: string | null;
  caption?: string | null;
  /**
   * Photographer or source.
   */
  credit?: string | null;
  /**
   * Usage/rights notes (e.g. licence, expiry).
   */
  rights?: string | null;
  /**
   * Required when the image shows identifiable people (privacy R9).
   */
  consentOnFile?: boolean | null;
  tags?: string | null;
  /**
   * Hide from the picker without deleting. Cannot archive an asset still in use.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-groups".
 */
export interface ServiceGroup {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * In-home care services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  group: number | ServiceGroup;
  /**
   * Short description used in cards/menus (≤ 200 chars).
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  whoFor?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedFunding?: (number | FundingProgram)[] | null;
  faqs?: (number | Faq)[] | null;
  downloads?: (number | Download)[] | null;
  order?: number | null;
  /**
   * How this page appears in search and when shared. Leave blank for sensible defaults.
   */
  seo?: {
    /**
     * ≤ 60 characters. Defaults to the title.
     */
    metaTitle?: string | null;
    /**
     * ≤ 160 characters. Defaults to the intro.
     */
    metaDescription?: string | null;
    /**
     * Only set if this content also lives at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Title when shared on social (defaults to meta title).
     */
    ogTitle?: string | null;
    /**
     * Description when shared (defaults to meta description).
     */
    ogDescription?: string | null;
    /**
     * Share image, ≥ 1200×630.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
    /**
     * Advanced: structured-data type. Leave as default unless advised.
     */
    structuredDataType?: ("WebPage" | "Article" | "Service" | "FAQPage") | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-programs".
 */
export interface FundingProgram {
  id: number;
  name: string;
  slug: string;
  shortCode: "SAH" | "CHSP" | "PRIVATE";
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  eligibility?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  priceLists?: (number | Download)[] | null;
  /**
   * How this page appears in search and when shared. Leave blank for sensible defaults.
   */
  seo?: {
    /**
     * ≤ 60 characters. Defaults to the title.
     */
    metaTitle?: string | null;
    /**
     * ≤ 160 characters. Defaults to the intro.
     */
    metaDescription?: string | null;
    /**
     * Only set if this content also lives at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Title when shared on social (defaults to meta title).
     */
    ogTitle?: string | null;
    /**
     * Description when shared (defaults to meta description).
     */
    ogDescription?: string | null;
    /**
     * Share image, ≥ 1200×630.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
    /**
     * Advanced: structured-data type. Leave as default unless advised.
     */
    structuredDataType?: ("WebPage" | "Article" | "Service" | "FAQPage") | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * Price lists, brochures, policy PDFs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  description?: string | null;
  category: "price-list" | "brochure" | "form" | "policy" | "guide";
  effectiveFrom?: string | null;
  isCareContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: "general" | "funding" | "services" | "getting-started" | "rights";
  isCareContent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * e.g. "Maria, daughter of a client".
   */
  attribution: string;
  /**
   * Must be ticked before this can be published (docs/09 §11).
   */
  consentOnFile: boolean;
  relatedService?: (number | null) | Service;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  intro?: string | null;
  /**
   * Build the page from approved blocks (docs/16).
   */
  sections?:
    | {
        id?: string | null;
      }[]
    | null;
  /**
   * How this page appears in search and when shared. Leave blank for sensible defaults.
   */
  seo?: {
    /**
     * ≤ 60 characters. Defaults to the title.
     */
    metaTitle?: string | null;
    /**
     * ≤ 160 characters. Defaults to the intro.
     */
    metaDescription?: string | null;
    /**
     * Only set if this content also lives at another URL.
     */
    canonicalUrl?: string | null;
    /**
     * Title when shared on social (defaults to meta title).
     */
    ogTitle?: string | null;
    /**
     * Description when shared (defaults to meta description).
     */
    ogDescription?: string | null;
    /**
     * Share image, ≥ 1200×630.
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noindex?: boolean | null;
    /**
     * Advanced: structured-data type. Leave as default unless advised.
     */
    structuredDataType?: ("WebPage" | "Article" | "Service" | "FAQPage") | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "service-groups";
        value: number | ServiceGroup;
      } | null)
    | ({
        relationTo: "services";
        value: number | Service;
      } | null)
    | ({
        relationTo: "funding-programs";
        value: number | FundingProgram;
      } | null)
    | ({
        relationTo: "faqs";
        value: number | Faq;
      } | null)
    | ({
        relationTo: "testimonials";
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: "downloads";
        value: number | Download;
      } | null)
    | ({
        relationTo: "pages";
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  sites?: T;
  status?: T;
  lastLoginAt?: T;
  failedLoginCount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  isDecorative?: T;
  altText?: T;
  caption?: T;
  credit?: T;
  rights?: T;
  consentOnFile?: T;
  tags?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-groups_select".
 */
export interface ServiceGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  summary?: T;
  body?: T;
  whoFor?: T;
  relatedFunding?: T;
  faqs?: T;
  downloads?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noindex?: T;
        structuredDataType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "funding-programs_select".
 */
export interface FundingProgramsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortCode?: T;
  summary?: T;
  body?: T;
  eligibility?: T;
  priceLists?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noindex?: T;
        structuredDataType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  isCareContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  consentOnFile?: T;
  relatedService?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  effectiveFrom?: T;
  isCareContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  sections?:
    | T
    | {
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noindex?: T;
        structuredDataType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide contact details and defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName: string;
  organisationLegalName: string;
  phonePrimary: string;
  email: string;
  address: {
    /**
     * Street address.
     */
    line1: string;
    /**
     * Unit/level (optional).
     */
    line2?: string | null;
    suburb: string;
    state: string;
    postcode: string;
    country: string;
    /**
     * Map coordinates (optional).
     *
     * @minItems 2
     * @maxItems 2
     */
    geo?: [number, number] | null;
  };
  /**
   * Confirm 1930 (see D7).
   */
  foundingYear: number;
  careSince?: number | null;
  defaultOgImage?: (number | null) | Media;
  acknowledgementOfCountry: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header menu. Phone and “Get started” are always shown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerItems?:
    | {
        label: string;
        link: {
          /**
           * What this link points to.
           */
          kind: "internal" | "external" | "email" | "tel" | "download" | "anchor";
          /**
           * Internal: the page to link to.
           */
          reference?:
            | ({
                relationTo: "pages";
                value: number | Page;
              } | null)
            | ({
                relationTo: "services";
                value: number | Service;
              } | null);
          /**
           * External: the full https:// address.
           */
          url?: string | null;
          /**
           * Email: the address.
           */
          email?: string | null;
          /**
           * Phone: the number.
           */
          phone?: string | null;
          /**
           * Download: the file.
           */
          file?: (number | null) | Download;
          /**
           * Section: the anchor id on this page.
           */
          anchor?: string | null;
          /**
           * Open in a new tab (used for external links).
           */
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer links, acknowledgement, and accreditations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading: string;
        links?:
          | {
              /**
               * What this link points to.
               */
              kind: "internal" | "external" | "email" | "tel" | "download" | "anchor";
              /**
               * Internal: the page to link to.
               */
              reference?:
                | ({
                    relationTo: "pages";
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: "services";
                    value: number | Service;
                  } | null);
              /**
               * External: the full https:// address.
               */
              url?: string | null;
              /**
               * Email: the address.
               */
              email?: string | null;
              /**
               * Phone: the number.
               */
              phone?: string | null;
              /**
               * Download: the file.
               */
              file?: (number | null) | Download;
              /**
               * Section: the anchor id on this page.
               */
              anchor?: string | null;
              /**
               * Open in a new tab (used for external links).
               */
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  acknowledgement: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  organisationLegalName?: T;
  phonePrimary?: T;
  email?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        suburb?: T;
        state?: T;
        postcode?: T;
        country?: T;
        geo?: T;
      };
  foundingYear?: T;
  careSince?: T;
  defaultOgImage?: T;
  acknowledgementOfCountry?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              kind?: T;
              reference?: T;
              url?: T;
              email?: T;
              phone?: T;
              file?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              kind?: T;
              reference?: T;
              url?: T;
              email?: T;
              phone?: T;
              file?: T;
              anchor?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  acknowledgement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
